easy_admin:
    entities:
        # List the entity class name you want to manage
        Astronaut:
            class: App\Entity\Astronaut
        Launcher:
            class: App\Entity\Launcher
        Mission:
            class: App\Entity\Mission
        User:
            class: App\Entity\User
